# SUM

In [1]:
sum([1,3])

4

In [4]:
sum([1,2,3,4])  #sum이라는 함수는 입력갯수 여러개 가능하네

10

In [2]:
#더하기 함수
def sum2(a,b):
    result=a+b
    return(result)

In [5]:
print(sum2(10,20))

30


In [13]:
#곱하기 함수
def multiple2(a,b):
    result=a*b
    return(result)

In [18]:
print(multiple2(10,2))

20


In [17]:

print(mul(10,20))

NameError: name 'mul' is not defined

In [24]:
#입력이 가변적인 함수 만들기
def sumrandom(*args):
    result=0
    print(type(args))          #가변 입력값은 튜플이네????
    for i in args:
        result+=i
    return result

print(sumrandom(1,2,3,4,5))
print(sumrandom(1,2,3,4,5,6,7,8,9,10))

<class 'tuple'>
15
<class 'tuple'>
55


In [35]:
def myFunction(func,*args):
    if func=="sum":
        sum_f=0
        for i in args:
            sum_f+=i
        return(sum_f)
    elif func=="count":
        return(len(args))
    else:
        return("No Function")

print(myFunction("sum",1,2,3,4,5))
print(myFunction("count",1,2,3,4,5))
print(myFunction("nono",1,2,3,4,5))


15
5
No Function


In [36]:
def multiFunc(a,b):
    return a+b,a*b,a/b,a-b
print(multiFunc(10,30))  #튜플 형식이라 다이렉트로 가공할 수 없음, list로 풀거나 다른 형식으로 변환 해야함

(40, 300, 0.3333333333333333, -20)


In [37]:
#함수의 범위 (지역변수)
a=1
def func(a):
    a+=10
    return a # 함수의 변수는 함수안에서가 나와바리임
print(func(a))
print(a)

11
1


In [38]:
#a+b의 기존의 함수형식으로 사용
def sum2(a,b):
    return a+b
sum2(10,20)

30

In [40]:
#lambda형식으로 지정하여 사용하고 다시 사용하려면 다시 작성해야 됨..
(lambda x,y: x+y)(10,20)

30

[과제] 함수의 입력인자는 2개가 있습니다.
1)입력인자1: sel1,sel2(sel1은 임의의 입력인자 2에 대한 모든 +,* 를 수행한다. sel2는 입력인자2 중에 가장 처음수와 가장 마지막수를 결과로 준다.)

2)입력인자2: 입력하는 숫자가 정해지지 않은 숫자들(단,2개 이상)

입력인자1이 지정한 것 이외의 것이 들어가면 "sel파라미터 확인해"메시지 출력

In [46]:
def myFunc(sel,*args): #(고정 변수, 가변 변수)
    if(sel=="sel1"):
        sum_1=0
        mul_1=1
        for i in args:
            sum_1+=i
            mul_1*=i
        return(sum_1,mul_1)
    elif(sel=="sel2"):
        return(args[0],args[len(args)-1])
    else:
        return("sel파라미터 확인해")

In [47]:
print(myFunc("sel1",1,2,3,4,5))
print(myFunc("sel2",1,2,3,4))
print(myFunc("sel",1,2,3,4,5))

(15, 120)
(1, 4)
sel파라미터 확인해


# Numpy

In [56]:
import numpy as np

In [59]:
np.array([1,2,3]) #np로 약어 사용했으면 np로만 호출해야 됨 .numpy쓰면 에러뜸 

array([1, 2, 3])

In [75]:
#파이썬 기본 자료 구조: 리스트      #이건 메모리상에 흩뿌려져 있어
a=[1,2,3,4,5]

In [79]:
# a에 일괄적으로 15씩 더하기
# 쌩 파이썬 이용
b=[]
for i in a:           #for문써야되서 귀찮음
    b.append(i+15)
b

[16, 17, 18, 19, 20]

In [52]:
numpy.array([1,2,3],[1,2,3])

TypeError: data type not understood

In [87]:
#numpy쓰면 한 줄로 가능
a=[1,2,3,4,5]
a=np.array(a)+15
a

array([16, 17, 18, 19, 20])

In [93]:
#두개의 리스트 더하기(원소끼리 더하기)
a=[1,2,3,4,5]
b=[1,2,3,4,5]
c=[]
# a+b 하면 a뒤에 b가 붙어버림. 원소끼리 더하는 게 아님
for i in range(0,len(a)):
    c.append(a[i]+b[i])
print(c)

[2, 4, 6, 8, 10]


In [101]:
#numpy써서 원소끼리 더하기
a=[1,2,3,4,5]
a=np.array(a)
b=[1,2,3,4,5]
b=np.array(b)
c=a+b
c

array([ 2,  4,  6,  8, 10])

In [105]:
#벡터 스칼라 연산
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print()
print(arr*arr)
print()
print(arr-arr)  #원소끼리 계산수행하네

[[1 2 3]
 [4 5 6]]

[[ 1  4  9]
 [16 25 36]]

[[0 0 0]
 [0 0 0]]


In [116]:
#ndarray 생성
data1=[6.,7.5,8,0.,1.]
arr1=np.array(data1)
arr1


array([6. , 7.5, 8. , 0. , 1. ])

In [118]:
print(arr1.ndim)
print(arr1.shape)
print(arr1.dtype)

1
(5,)
float64


In [113]:
arr1[0]

6.0

In [119]:
#어레이 원소 타입 변경
temp=np.array([1,2,3], dtype=np.string_)  #string 문자열로 변경
temp

array([b'1', b'2', b'3'], dtype='|S1')

In [120]:
# numpy array vs Python Lsit speed
# 물론 조건 및 여러 상황에 따라서 조금 다를 수 있으니 참고!

# 01) 아래는 두 개의 리스트에서 각기 리스트의 합을 구하는 경우
# ( 코드 상 차이가 발생하는 부분들 : range, 리스트에서 +는 리스트 연결이나, numpy에서는 각기 원소들의 합
# 따라서 동일한 역할을 위해서는 리스트에서는for가 필요함

import time
size_vector = 100000

def pythonlist(size_vector):
    t1 = time.time()
    x = range(size_vector)
    y = range(size_vector)
    t2 = time.time()
    print ("python list Load Time : " + str(t2-t1))
    z = []
    
    t3 = time.time()
    for i in range(len(x)):
        z.append(x[i] + y[i])
    t4 = time.time()
    print ("python list for loop : " + str(t4- t3))
    
    print (" Python List Total :" + str(t4 - t1))

    
def numpyarray1(size_vector):
    t1 = time.time()
    x = np.arange(size_vector)
    y = np.arange(size_vector)
    t2 = time.time()
    print ("numpy array1 Load Time : "+str(t2-t1))
    
    t3 = time.time()
    z = x + y
    t4 = time.time()
    print ("numpy array1 for loop : " + str(t4- t3))

    print (" numpy array1 Total :" + str(t4 - t1))

def numpyarray2(size_vector):
    t1 = time.time()
    x = np.arange(size_vector)
    y = np.arange(size_vector)
    t2 = time.time()
    print ("numpy array2 Load Time : "+str(t2-t1))
    
    t3 = time.time()
    z = np.ndarray(size_vector)
    for i in range(len(x)):
        z[i] = x[i] + y[i]
    t4 = time.time()
    print ("numpy array2 for loop : " + str(t4- t3))
    print (" numpy array2 Total :" + str(t4 - t1))

print (" size_vector : 100000")
pythonlist(size_vector)
numpyarray1(size_vector)
numpyarray2(size_vector)
print ("------------------------------")

print (" size_vector : 100")
size_vector = 100
pythonlist(size_vector)
numpyarray1(size_vector)
numpyarray2(size_vector)
print ("------------------------------")


#  샘플 결과 
# -->기본적으로 일반적인 list로 생성하는 것이 array로 생성하는 것에 비해서 많은 속도가 소욧된다.
# --> numpy의 백터 연산이 기본적인 for에서 append보다 속도가 빠른 것을 볼 수 있음.
# --> 동잉한 for에 대해서도 상당히 속도가 빠른 것을 볼 수 있다. 
# --> 작은 숫자에서는 큰 차이가 없거나 경우에 따라서 List가 빠를 수도 있음.


# 하나의 예시 결과

#  size_vector : 100000
# python list Load Time : 2.86102294921875e-06
# python list for loop : 0.05470418930053711
#  Python List Total :0.05480003356933594
# numpy array1 Load Time : 0.0014030933380126953
# numpy array1 for loop : 0.0006737709045410156
#  numpy array1 Total :0.002165079116821289
# numpy array2 Load Time : 0.00037980079650878906
# numpy array2 for loop : 1.0013580322265625e-05
#  numpy array2 Total :0.0004830360412597656
# ------------------------------
#  size_vector : 100
# python list Load Time : 3.0994415283203125e-06
# python list for loop : 4.7206878662109375e-05
#  Python List Total :0.00010013580322265625
# numpy array1 Load Time : 5.125999450683594e-05
# numpy array1 for loop : 1.621246337890625e-05
#  numpy array1 Total :0.0001232624053955078
# numpy array2 Load Time : 1.2159347534179688e-05
# numpy array2 for loop : 6.9141387939453125e-06
#  numpy array2 Total :6.818771362304688e-05
# ------------------------------

 size_vector : 100000
python list Load Time : 0.0
python list for loop : 0.035982608795166016
 Python List Total :0.035982608795166016
numpy array1 Load Time : 0.0009815692901611328
numpy array1 for loop : 0.0
 numpy array1 Total :0.0009815692901611328
numpy array2 Load Time : 0.000997304916381836
numpy array2 for loop : 0.03388619422912598
 numpy array2 Total :0.03488349914550781
------------------------------
 size_vector : 100
python list Load Time : 0.0
python list for loop : 0.0
 Python List Total :0.0
numpy array1 Load Time : 0.0
numpy array1 for loop : 0.0
 numpy array1 Total :0.0
numpy array2 Load Time : 0.0
numpy array2 for loop : 0.0
 numpy array2 Total :0.0
------------------------------


In [122]:
### 속도 비교 : 각기 원소들의 제곱들로 만드는 것.

In [124]:
# 02) 속도 비교
# 제곱 결과들

def square_list0(N):
    squares = []
    for n in range(N):
        squares = squares + [n**2]
    return squares


def square_list1(N):
    squares = []
    for n in range(N):
        # 일반적으로 생성해서 더하는 방법
        squares += [n**2]
    return squares
    

def square_list2(N):
    squares = []
    for n in range(N):
        # append 라고 이미 정의된 메소드 이용하는 방법
        squares.append(n**2)
    return squares
    

def square_list3(N):
    # 동일한 방법이나 벡터연산으로 처리
    return [n**2 for n in range(N)]
    

def square_array(N):
    # Vectorize the entire operation.
    #from numpy import arange
    #return arange(N)**2
    return np.arange(N)**2


n = 100
print("Number :" ,n)
t1 = time.time()
square_list0(n)
t2 = time.time()
print ("List0-Try : ",t2-t1)

t1 = time.time()
square_list1(n)
t2 = time.time()
print ("List1-Try : ",t2-t1)

t1 = time.time()
square_list2(n)
t2 = time.time()
print ("List2-Try : ",t2-t1)

t1 = time.time()
square_list3(n)
t2 = time.time()
print ("List3-Try : ",t2-t1)

t1 = time.time()
square_array(n)
t2 = time.time()
print ("Array-Try : ",t2-t1)
print ("---------------")

n = 100000
print("Number :", n)
t1 = time.time()
square_list0(n)
t2 = time.time()
print ("List0-Try : ",t2-t1)

t1 = time.time()
square_list1(n)
t2 = time.time()
print ("List1-Try : ",t2-t1)

t1 = time.time()
square_list2(n)
t2 = time.time()
print ("List2-Try : ",t2-t1)

t1 = time.time()
square_list3(n)
t2 = time.time()
print ("List3-Try : ",t2-t1)

t1 = time.time()
square_array(n)
t2 = time.time()
print ("Array-Try : ",t2-t1)



# 결과 
# ---> 리스트를 사용할 것이라면 그래도 내부적으로 정의된 append가 빠르며
# ---> 리스트를 사용할 때 이보다더 더 빠르게 사용하려면 "벡터연산"으로 코드를 변경할 것
# ---> 이보다도 numpy가 더 빠르다. 특히 n이 작으면 차이가 별로 없으나, 커질수록 많이 차이가 남!!!

# ------------------------------------------------------------
# Number : 100
# List0-Try :  0.00013494491577148438
# List1-Try :  9.608268737792969e-05
# List2-Try :  9.298324584960938e-05
# List3-Try :  8.702278137207031e-05
# Array-Try :  0.00011014938354492188
# ---------------
# Number : 100000
# List0-Try :  33.61902904510498
# List1-Try :  0.049868106842041016
# List2-Try :  0.04886770248413086
# List3-Try :  0.03975033760070801
# Array-Try :  0.0006237030029296875

Number : 100
List0-Try :  0.0009741783142089844
List1-Try :  0.0
List2-Try :  0.0
List3-Try :  0.0
Array-Try :  0.0
---------------
Number : 100000
List0-Try :  11.562129735946655
List1-Try :  0.031914472579956055
List2-Try :  0.028925418853759766
List3-Try :  0.0259091854095459
Array-Try :  0.0


In [126]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
#astype이용해서 이미 불러온 array 타입 변경

In [128]:
#색인

In [129]:
list1=[1,2,3,4,5]
arr1=np.array(list1)
print(list1)
print(arr1)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [132]:
print(list1[0])
print(arr1[0])
print(list1[1:3])
print(arr1[1:3])
print(list1[3:])
print(arr1[3:])
print(list1[:])
print(arr1[:])

1
1
[2, 3]
[2 3]
[4, 5]
[4 5]
[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [134]:
arr1=np.arange(10)
print(arr1[2:9:3])

[2 5 8]


In [148]:
arr=np.arange(0,6,1)
arr

array([0, 1, 2, 3, 4, 5])

In [150]:
arr= np.arange(0,51,10)[:,np.newaxis] # 축 변경 newaxis
arr=arr+np.arange(0,6,1) #(1X5)행렬과 (5X1)행렬 합치기
arr

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [166]:
print(arr[0][3:5]) #큰원소를 보고 작은원소 접근하는 방법
print(arr[0,3:5]) #행렬을 하나의 큰 행렬로 보고 바로 접근하는 방법.
print(arr[:,2][:,np.newaxis])
print(arr[2:5:2,0:5:2])
print(arr[4:6,4:6])

[3 4]
[3 4]
[[ 2]
 [12]
 [22]
 [32]
 [42]
 [52]]
[[20 22 24]
 [40 42 44]]
[[44 45]
 [54 55]]


In [172]:
#boolean indexing
arr1=np.arange(10)
print(arr1)
print(arr1<5)
print(arr1[arr1<5])

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]
